/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas;

/**
 *
 * @author saimo
 */
public class ElevadorPorFuera extends javax.swing.JPanel {

    /**
     * Creates new form Elevador
     */
    public ElevadorPorFuera() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        AdentroAscensor = new javax.swing.JPanel();
        PuertaDerechaAscensor = new javax.swing.JPanel();
        PuertaIzquierdaAscensor = new javax.swing.JPanel();

        setBackground(new java.awt.Color(115, 115, 115));
        setLayout(null);

        jButton1.setText(".");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(990, 450, 40, 40);

        jButton2.setText(".");
        add(jButton2);
        jButton2.setBounds(990, 510, 40, 40);

        PuertaDerechaAscensor.setBackground(new java.awt.Color(102, 255, 255));

        javax.swing.GroupLayout PuertaDerechaAscensorLayout = new javax.swing.GroupLayout(PuertaDerechaAscensor);
        PuertaDerechaAscensor.setLayout(PuertaDerechaAscensorLayout);
        PuertaDerechaAscensorLayout.setHorizontalGroup(
            PuertaDerechaAscensorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
        );
        PuertaDerechaAscensorLayout.setVerticalGroup(
            PuertaDerechaAscensorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        PuertaIzquierdaAscensor.setBackground(new java.awt.Color(102, 255, 255));

        javax.swing.GroupLayout PuertaIzquierdaAscensorLayout = new javax.swing.GroupLayout(PuertaIzquierdaAscensor);
        PuertaIzquierdaAscensor.setLayout(PuertaIzquierdaAscensorLayout);
        PuertaIzquierdaAscensorLayout.setHorizontalGroup(
            PuertaIzquierdaAscensorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
        );
        PuertaIzquierdaAscensorLayout.setVerticalGroup(
            PuertaIzquierdaAscensorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout AdentroAscensorLayout = new javax.swing.GroupLayout(AdentroAscensor);
        AdentroAscensor.setLayout(AdentroAscensorLayout);
        AdentroAscensorLayout.setHorizontalGroup(
            AdentroAscensorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdentroAscensorLayout.createSequentialGroup()
                .addComponent(PuertaIzquierdaAscensor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(PuertaDerechaAscensor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        AdentroAscensorLayout.setVerticalGroup(
            AdentroAscensorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PuertaDerechaAscensor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PuertaIzquierdaAscensor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(AdentroAscensor);
        AdentroAscensor.setBounds(450, 190, 510, 560);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdentroAscensor;
    private javax.swing.JPanel PuertaDerechaAscensor;
    private javax.swing.JPanel PuertaIzquierdaAscensor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
