/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas;

import Funcionamientos.ElevadorEstado;

import static Ventanas.MenuPrincipal.ElevadorPorDentroVentana;
import static Ventanas.MenuPrincipal.ElevadorPorFueraVentana;
import static Ventanas.MenuPrincipal.MenuInicioVentana;


/**
 *
 * @author saimo
 */
public class ElevadorPorFuera extends javax.swing.JPanel {

    /**
     * Creates new form ElevadorPorFuera
     */
    public ElevadorPorFuera() {
        initComponents();
        ContadorPisos.setText(ElevadorEstado.getPisoActual());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Salir = new javax.swing.JButton();
        Ascensor = new javax.swing.JPanel();
        PuertaDerecha = new javax.swing.JPanel();
        PuertaIzquierda = new javax.swing.JPanel();
        LetreroMaximoPersonas = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Boton_Subir = new javax.swing.JToggleButton();
        Boton_Bajar = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        ContadorPisos = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        Boton_VerAscensorPorDentro = new javax.swing.JButton();
        SelectorDePiso = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1400, 750));
        setLayout(null);

        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-ventana-50.png"))); // NOI18N
        Salir.setBorderPainted(false);
        Salir.setContentAreaFilled(false);
        Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salir.setFocusPainted(false);
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalirMouseExited(evt);
            }
        });
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        add(Salir);
        Salir.setBounds(10, 10, 40, 40);

        Ascensor.setLayout(null);

        PuertaDerecha.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout PuertaDerechaLayout = new javax.swing.GroupLayout(PuertaDerecha);
        PuertaDerecha.setLayout(PuertaDerechaLayout);
        PuertaDerechaLayout.setHorizontalGroup(
            PuertaDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        PuertaDerechaLayout.setVerticalGroup(
            PuertaDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Ascensor.add(PuertaDerecha);
        PuertaDerecha.setBounds(220, 0, 220, 540);

        PuertaIzquierda.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout PuertaIzquierdaLayout = new javax.swing.GroupLayout(PuertaIzquierda);
        PuertaIzquierda.setLayout(PuertaIzquierdaLayout);
        PuertaIzquierdaLayout.setHorizontalGroup(
            PuertaIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        PuertaIzquierdaLayout.setVerticalGroup(
            PuertaIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        Ascensor.add(PuertaIzquierda);
        PuertaIzquierda.setBounds(0, 0, 210, 540);

        add(Ascensor);
        Ascensor.setBounds(480, 210, 440, 540);

        LetreroMaximoPersonas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MaximaCantidadPersonas.png"))); // NOI18N
        LetreroMaximoPersonas.setBorderPainted(false);
        LetreroMaximoPersonas.setContentAreaFilled(false);
        LetreroMaximoPersonas.setFocusPainted(false);
        LetreroMaximoPersonas.setFocusable(false);
        add(LetreroMaximoPersonas);
        LetreroMaximoPersonas.setBounds(210, 70, 210, 140);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(null);

        Boton_Subir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/arriba-en-círculo-30-negro.png"))); // NOI18N
        Boton_Subir.setBorderPainted(false);
        Boton_Subir.setContentAreaFilled(false);
        Boton_Subir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton_Subir.setFocusPainted(false);
        Boton_Subir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Boton_SubirMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Boton_SubirMouseReleased(evt);
            }
        });
        Boton_Subir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_SubirActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Subir);
        Boton_Subir.setBounds(10, 10, 30, 30);

        Boton_Bajar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/abajo-en-círculo-30-negro.png"))); // NOI18N
        Boton_Bajar.setBorderPainted(false);
        Boton_Bajar.setContentAreaFilled(false);
        Boton_Bajar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton_Bajar.setFocusPainted(false);
        Boton_Bajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_BajarActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Bajar);
        Boton_Bajar.setBounds(10, 40, 30, 30);

        add(jPanel1);
        jPanel1.setBounds(930, 450, 50, 80);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        ContadorPisos.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        ContadorPisos.setForeground(new java.awt.Color(255, 0, 0));
        ContadorPisos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ContadorPisos.setText("S1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContadorPisos, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContadorPisos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        add(jPanel2);
        jPanel2.setBounds(650, 110, 90, 90);
        add(jSpinner1);
        jSpinner1.setBounds(60, 330, 40, 26);

        Boton_VerAscensorPorDentro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ascensorPorDentro-50.png"))); // NOI18N
        Boton_VerAscensorPorDentro.setBorderPainted(false);
        Boton_VerAscensorPorDentro.setContentAreaFilled(false);
        Boton_VerAscensorPorDentro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton_VerAscensorPorDentro.setFocusPainted(false);
        Boton_VerAscensorPorDentro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Boton_VerAscensorPorDentroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Boton_VerAscensorPorDentroMouseExited(evt);
            }
        });
        Boton_VerAscensorPorDentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_VerAscensorPorDentroActionPerformed(evt);
            }
        });
        add(Boton_VerAscensorPorDentro);
        Boton_VerAscensorPorDentro.setBounds(930, 200, 60, 60);

        SelectorDePiso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Piso S1", "Piso 1", "Piso 2", "Piso 3" }));
        SelectorDePiso.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SelectorDePiso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(SelectorDePiso);
        SelectorDePiso.setBounds(20, 300, 80, 26);
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_SubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_SubirActionPerformed
        Boton_Subir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/arriba-en-círculo-30.png")));
        cerrarElevador();
        ElevadorPorDentroVentana.abrirElevador();
        
    }//GEN-LAST:event_Boton_SubirActionPerformed

    private void Boton_BajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_BajarActionPerformed
        Boton_Bajar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/abajo-en-círculo-30.png")));
        abrirElevador();
        ElevadorPorDentroVentana.cerrarElevador();
    }//GEN-LAST:event_Boton_BajarActionPerformed

    private void SalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseEntered
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-ventana-45.png")));
       
    }//GEN-LAST:event_SalirMouseEntered

    private void SalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseExited
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-ventana-50.png")));
    }//GEN-LAST:event_SalirMouseExited

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        ElevadorPorDentroVentana.setVisible(false);
        ElevadorPorFueraVentana.setVisible(false);
        MenuInicioVentana.setVisible(true);
    }//GEN-LAST:event_SalirActionPerformed

    private void Boton_SubirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_SubirMousePressed
        
    }//GEN-LAST:event_Boton_SubirMousePressed

    private void Boton_SubirMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_SubirMouseReleased
       
    }//GEN-LAST:event_Boton_SubirMouseReleased

    private void Boton_VerAscensorPorDentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_VerAscensorPorDentroActionPerformed
        ElevadorPorDentroVentana.setVisible(true);
        ElevadorPorDentroVentana.actualizarContadorPisos(ElevadorEstado.getPisoActual());
        ElevadorPorFueraVentana.setVisible(false);
        MenuInicioVentana.setVisible(false);
    }//GEN-LAST:event_Boton_VerAscensorPorDentroActionPerformed

    private void Boton_VerAscensorPorDentroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_VerAscensorPorDentroMouseEntered
        Boton_VerAscensorPorDentro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ascensorPorDentro-45.png")));
    }//GEN-LAST:event_Boton_VerAscensorPorDentroMouseEntered

    private void Boton_VerAscensorPorDentroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_VerAscensorPorDentroMouseExited
        Boton_VerAscensorPorDentro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ascensorPorDentro-50.png")));
    }//GEN-LAST:event_Boton_VerAscensorPorDentroMouseExited
    
    public void cerrarElevador(){
        Animacion.Animacion.mover_derecha(220, 412, 15, 5, PuertaDerecha);
        Animacion.Animacion.mover_izquierda(0, -180, 15, 5, PuertaIzquierda);
    }
    
    public void abrirElevador(){
        Animacion.Animacion.mover_izquierda(412, 220, 15, 5, PuertaDerecha);
        Animacion.Animacion.mover_derecha(-180, 0, 15, 5, PuertaIzquierda);
    }
    public void actualizarContadorPisos() {
    ContadorPisos.setText(Funcionamientos.ElevadorEstado.getPisoActual());
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Ascensor;
    private javax.swing.JToggleButton Boton_Bajar;
    private javax.swing.JToggleButton Boton_Subir;
    private javax.swing.JButton Boton_VerAscensorPorDentro;
    private javax.swing.JLabel ContadorPisos;
    private javax.swing.JButton LetreroMaximoPersonas;
    private javax.swing.JPanel PuertaDerecha;
    private javax.swing.JPanel PuertaIzquierda;
    private javax.swing.JButton Salir;
    private javax.swing.JComboBox<String> SelectorDePiso;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
