/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import java.awt.BorderLayout;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import java.util.ArrayList;

/**
 *
 * @author saimo
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    
    public static ElevadorPorFuera ElevadorPorFueraVentana = new ElevadorPorFuera();
    public static ElevadorPorDentro ElevadorPorDentroVentana = new ElevadorPorDentro();
    public static MenuInicio MenuInicioVentana = new MenuInicio();
    public static ArrayList<String> pisosStringList = new ArrayList<>();
    
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        iniciarPrograma();
        //setIconImage(new ImageIcon(getClass().getResource("../imagenes/elevatorIcon.png")).getImage());
        this.setTitle("Sistema De Elevadores - Grupo 5 - Prototipo_1");
        pisosStringList.add("S1");
        pisosStringList.add("1");
        pisosStringList.add("2");
        pisosStringList.add("3");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelJFrame = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelJFrame.setBackground(new java.awt.Color(204, 204, 204));
        PanelJFrame.setToolTipText("");
        PanelJFrame.setLayout(null);
        getContentPane().add(PanelJFrame, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jMenu1.setText("Inicio");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Vista");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Info");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
                MenuInicioVentana.setVisible(true);
                
               
            }
        });
    }
    
    private void iniciarPrograma(){
        ShowJPanel(ElevadorPorFueraVentana);
        ShowJPanel(ElevadorPorDentroVentana);
        ShowJPanel(MenuInicioVentana);
        MenuInicioVentana.setVisible(true);

    }
    
    private void ShowJPanel(JPanel p){
        p.setSize(1400,750);
        p.setLocation(0,0);
        PanelJFrame.add(p, BorderLayout.CENTER);
        PanelJFrame.revalidate();
        PanelJFrame.repaint();
        p.setVisible(false);
    }     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelJFrame;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
